name: "Build"

on:
  push:
    branches:
      - main
      - develop
    paths-ignore: 
      - '.github/**'

jobs:
  deploy-terraform:
    uses: eduzuchetti/ez-devops-gh-actions/.github/workflows/pipeline-terraform-module.yml@main
    secrets: inherit
    with:
      sonar-scan: false
      terraform-version: 1.11.2
      node-version: 22
